# Generated by claude
import cv2

drone_url = "rtsp://192.168.1.1:7070/webcam"
cap = cv2.VideoCapture(drone_url)

# Get frame properties
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS)) or 30

fourcc = cv2.VideoWriter_fourcc(*'mp4v') # type: ignore
out = None
recording = False

print("Press 'r' to start/stop recording, 'q' to quit")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Write frame if recording
    if recording and out is not None:
        out.write(frame)
    
    cv2.imshow('Frame', frame)
    
    key = cv2.waitKey(1) & 0xFF
    
    if key == ord('r'):
        if not recording:
            # Start recording
            out = cv2.VideoWriter('output_light.mp4', fourcc, fps, (width, height))
            recording = True
            print("Started recording")
        else:
            # Stop recording
            recording = False
            if out is not None:
                out.release()
            print("Stopped recording")
    elif key == ord('p'):
        cv2.imwrite('snapshot.png', frame)
        print("Snapshot saved as snapshot.png")
    elif key == ord('q'):
        break

cap.release()
if out is not None:
    out.release()
cv2.destroyAllWindows()