# PIDController generated by claude
import time

class PIDController:
    def __init__(self, kp, ki, kd, setpoint=0):
        self.kp = kp  # Proportional gain
        self.ki = ki  # Integral gain
        self.kd = kd  # Derivative gain
        
        self.setpoint = setpoint  # Target value (e.g., 0 = centered)
        
        self.previous_error = 0
        self.integral = 0
        self.last_time = time.time()
    
    def update(self, current_value):
        """Calculate control output based on current measurement"""
        current_time = time.time()
        dt = current_time - self.last_time
        
        # Calculate error
        error = self.setpoint - current_value
        
        # Proportional term
        p_term = self.kp * error
        
        # Integral term (accumulated error)
        self.integral += error * dt
        i_term = self.ki * self.integral
        
        # Derivative term (rate of change)
        derivative = (error - self.previous_error) / dt if dt > 0 else 0
        d_term = self.kd * derivative
        
        # Store for next iteration
        self.previous_error = error
        self.last_time = current_time
        
        # Combined output
        output = p_term + i_term + d_term
        
        return output
    
    def reset(self):
        """Reset integral and derivative terms"""
        self.integral = 0
        self.previous_error = 0
        self.last_time = time.time()